on: [push, pull_request]
name: CI Checks
jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git submodule update --init --recursive
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.0.0
      - run: poetry install
      - run: poetry run pytest
      - run: poetry run black . --check
      - run: poetry build
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
