on: [push, pull_request]
name: CI Checks
jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git submodule update --init --recursive
      - run: sudo apt-get update
      - run: sudo apt-get install -y tox
      - uses: actions/setup-python@v1
      - run: tox
      - run: python3 -m pip install build --user
      - run: python3 -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
