on: [push, pull_request]
name: CI Checks
jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git submodule update --init --recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: '1.3.2'
      - run: poetry install
      - run: poetry run pytest
      - run: poetry run black . --check
      - run: poetry build
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
